# This is a basic workflow to help you get started with Actions

name: Re-Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.CAN_SSH_HOST }}
          port: ${{ secrets.CAN_SSH_PORT }}
          username: ${{ secrets.CAN_SSH_USERNAME }}
          password: ${{ secrets.CAN_SSH_PASSWORD }}
          script: |
            cd /home/containers/MinifieDnD/app/
            git pull
            npm install
            npm run build
            pm2 restart static-page-server-3000
